//! Stable bridge-facing API surface.
//!
//! This crate intentionally has no native transport dependency. napi-rs, CLI,
//! and test transports live in sibling crates.

mod brain_stream;
mod buffers;

pub use brain_stream::{
    brain_wake_stream_channel, BrainWakeStream, BrainWakeStreamProducer, BrainWakeStreamSender,
};
pub use buffers::{
    BrainWakeBufferInput, BufferedBrainWakeRequest, RuntimeBufferLease, RuntimeBufferStore,
    APPLICATION_JSON, TEXT_PLAIN,
};
pub use rusty_crew_core_config::{ClockConfig, EngineConfig, EngineStorageConfig};
pub use rusty_crew_core_protocol::*;

pub const MANIFEST_VERSION: u32 = 1;
pub const MANIFEST_TEXT: &str = include_str!("../bridge-manifest.toml");
pub const WIRE_SHAPE_FINGERPRINT_TEXT: &str = include_str!("../bridge-wire-shape-fingerprint.txt");
pub const OPERATION_NAMES: &[&str] = &[
    "initialize_engine",
    "shutdown_engine",
    "register_brain_implementation",
    "replace_brain_implementation",
    "unregister_brain_implementation_for_profile",
    "wake_brain",
    "submit_brain_event",
    "submit_brain_actions",
    "apply_brain_provider_state_output",
    "brain_catalog",
    "plan_brain_selection",
    "start_brain_run",
    "drain_brain_run",
    "submit_brain_host_result",
    "cancel_brain_run",
    "buffered_brain_run_diagnostics",
    "cleanup_buffered_brain_runs",
    "exchange_openai_oauth_code",
    "register_platform_adapter",
    "validate_tool_metadata_policy",
    "validate_local_tool_profile_policy",
    "plan_tool_availability",
    "plan_local_code_resource_policy",
    "plan_web_browser_resource_policy",
    "validate_runtime_config_draft",
    "plan_runtime_config",
    "plan_create_profile",
    "plan_profile_registry_mutation",
    "plan_new_session_control",
    "plan_reload_mcp_control",
    "plan_channel_ingress_route",
    "plan_den_product_ingress_policy",
    "inject_external_event",
    "inject_den_data_update",
    "enqueue_body_follow_up_message",
    "archive_session",
    "ensure_configured_session",
    "register_scheduled_wake_job",
    "register_scheduled_host_job",
    "list_scheduled_jobs",
    "list_scheduled_runs",
    "claim_scheduled_host_runs",
    "request_scheduled_host_job_run",
    "complete_scheduled_host_run",
    "run_scheduler_tick",
    "request_scheduled_job_run",
    "pause_scheduled_job",
    "resume_scheduled_job",
    "plan_delegated_role_lifecycle",
    "cancel_delegated_session",
    "request_delegated_checkpoint",
    "drain_delegated_sessions",
    "cleanup_delegated_resources",
    "delegated_session_status",
    "list_sessions",
    "project_body_state",
    "provider_state_diagnostics",
    "save_message_slot",
    "save_message_variant",
    "create_chat_message_slot",
    "create_chat_message_variant",
    "chat_read_model_page",
    "append_chat_event",
    "query_chat_events",
    "query_message_slots",
    "query_message_variants",
    "select_active_message_variant",
    "select_active_chat_message_variant",
    "delete_chat_message_variant",
    "reorder_chat_message_variants",
    "delete_message_variant",
    "reorder_message_variants",
    "save_conversation_branch",
    "create_chat_conversation_branch",
    "ensure_active_chat_conversation_branch",
    "query_conversation_branches",
    "get_conversation_branch_state",
    "select_active_conversation_branch",
    "update_conversation_branch_head",
    "save_conversation_snapshot",
    "create_chat_conversation_snapshot",
    "query_conversation_snapshots",
    "resolve_conversation_jump",
    "save_attachment",
    "create_chat_attachment",
    "query_attachments",
    "remove_attachment",
    "remove_chat_attachment",
    "save_data_bank_scope",
    "create_chat_data_bank_scope",
    "query_data_bank_scopes",
    "remove_data_bank_scope",
    "remove_chat_data_bank_scope",
    "database_size",
    "storage_schema",
    "create_profile_registry_record",
    "update_profile_registry_record",
    "list_profile_registry_records",
    "get_profile_registry_record",
    "purge_profile",
    "upsert_model_provider",
    "list_model_providers",
    "get_model_provider",
    "get_model_provider_secret",
    "model_provider_refresh_impact",
    "plan_model_provider_refresh",
    "plan_roleplay_assistant_alternative",
    "plan_roleplay_session_lifecycle",
    "plan_roleplay_chat_layer_binding",
    "normalize_roleplay_lore_search_controls",
    "read_roleplay_scene_state",
    "plan_roleplay_scene_state_update",
    "build_roleplay_prompt_context",
    "roleplay_speaker_identity",
    "write_roleplay_character",
    "merge_roleplay_character",
    "write_roleplay_player_persona",
    "merge_roleplay_player_persona",
    "patch_roleplay_session_metadata",
    "normalize_roleplay_narrator_config",
    "start_roleplay_narrator_turn",
    "advance_roleplay_narrator_turn",
    "create_lore_layer",
    "get_lore_layer",
    "list_lore_layers",
    "update_lore_layer",
    "archive_lore_layer",
    "set_chat_layers",
    "get_chat_layers",
    "toggle_chat_layer",
    "reorder_chat_layers",
    "add_lore_entry",
    "replace_lore_entry",
    "supersede_lore_entry",
    "tombstone_lore_entry",
    "query_lore_entries",
    "get_lore_entry",
    "lore_entry_provenance_events",
    "add_entry_to_layer",
    "remove_entry_from_layer",
    "set_entry_constant",
    "list_entries_by_layer",
    "recall_lore",
    "capture_lore_fact",
    "promote_lore_entry",
    "get_lore_layer_config",
    "set_lore_layer_config",
    "list_recall_traces",
    "get_recall_trace",
    "list_simple_kv",
    "put_simple_kv",
    "delete_simple_kv",
    "storage_diagnostics",
    "run_maintenance",
    "list_memory_space_descriptors",
    "query_session_memory_records",
    "build_session_memory_prompt_context",
    "save_memory_proposal",
    "plan_capture_memory_proposals",
    "plan_curator_governance_transition",
    "plan_curator_lifecycle_transition",
    "plan_background_memory_auto_mutations",
    "list_memory_proposals",
    "save_session_activity_digest",
    "list_session_activity_digests",
    "save_context_compaction_artifact",
    "list_context_compaction_artifacts",
    "record_memory_governance_decision",
    "subscribe_events",
    "unsubscribe_events",
    "get_buffer",
    "release_buffer",
];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BridgeManifestSummary {
    pub version: u32,
    pub owning_crate: &'static str,
    pub native_package: &'static str,
    pub operation_names: &'static [&'static str],
}

pub fn manifest_summary() -> BridgeManifestSummary {
    BridgeManifestSummary {
        version: MANIFEST_VERSION,
        owning_crate: "rusty-crew-core-bridge-api",
        native_package: "@rusty-crew/native-bridge",
        operation_names: OPERATION_NAMES,
    }
}

pub fn wire_shape_fingerprint() -> &'static str {
    WIRE_SHAPE_FINGERPRINT_TEXT.trim()
}
