/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeBridgeBinding {
  validateToolMetadataPolicyJson(inputJson: string): string
  validateLocalToolProfilePolicyJson(inputJson: string): string
  planToolAvailabilityJson(inputJson: string): string
  validateRuntimeConfigDraftJson(inputJson: string): string
  planCreateProfileJson(inputJson: string): string
  planProfileRegistryMutationJson(inputJson: string): string
  planNewSessionControlJson(inputJson: string): string
  planReloadMcpControlJson(inputJson: string): string
  planDelegatedRoleLifecycleJson(inputJson: string): string
  planChannelIngressRouteJson(inputJson: string): string
  planDenProductIngressPolicyJson(inputJson: string): string
  planRuntimeConfigJson(inputJson: string): string
  createProfileRegistryRecordJson(writeJson: string): string
  updateProfileRegistryRecordJson(updateJson: string): string
  listProfileRegistryRecordsJson(queryJson: string): string
  getProfileRegistryRecordJson(profileId: string): string
  purgeProfileJson(profileId: string): string
  upsertModelProviderJson(writeJson: string): string
  listModelProvidersJson(queryJson: string): string
  getModelProviderJson(alias: string): string
  getModelProviderSecretJson(alias: string): string
  modelProviderRefreshImpactJson(requestJson: string): string
  planModelProviderRefreshJson(requestJson: string): string
  saveMessageSlotJson(inputJson: string): void
  saveMessageVariantJson(inputJson: string): string
  createChatMessageSlotJson(inputJson: string): string
  createChatMessageVariantJson(inputJson: string): string
  queryMessageSlotsJson(inputJson: string): string
  queryMessageVariantsJson(inputJson: string): string
  chatReadModelPageJson(inputJson: string): string
  appendChatEventJson(inputJson: string): string
  queryChatEventsJson(inputJson: string): string
  saveConversationBranchJson(inputJson: string): string
  createChatConversationBranchJson(inputJson: string): string
  ensureActiveChatConversationBranchJson(inputJson: string): string
  queryConversationBranchesJson(inputJson: string): string
  getConversationBranchStateJson(inputJson: string): string
  selectActiveConversationBranchJson(inputJson: string): string
  updateConversationBranchHeadJson(inputJson: string): string
  saveConversationSnapshotJson(inputJson: string): string
  createChatConversationSnapshotJson(inputJson: string): string
  queryConversationSnapshotsJson(inputJson: string): string
  resolveConversationJumpJson(inputJson: string): string
  saveAttachmentJson(inputJson: string): string
  createChatAttachmentJson(inputJson: string): string
  queryAttachmentsJson(inputJson: string): string
  removeAttachmentJson(inputJson: string): string
  removeChatAttachmentJson(inputJson: string): string
  saveDataBankScopeJson(inputJson: string): string
  createChatDataBankScopeJson(inputJson: string): string
  queryDataBankScopesJson(inputJson: string): string
  removeDataBankScopeJson(inputJson: string): string
  removeChatDataBankScopeJson(inputJson: string): string
  selectActiveMessageVariantJson(inputJson: string): string
  selectActiveChatMessageVariantJson(inputJson: string): string
  deleteChatMessageVariantJson(inputJson: string): string
  reorderChatMessageVariantsJson(inputJson: string): string
  deleteMessageVariantJson(inputJson: string): string
  reorderMessageVariantsJson(inputJson: string): string
  cancelDelegatedSession(delegatedSessionId: string): JsSessionState
  requestDelegatedCheckpoint(parentSessionId: string, delegatedSessionId: string, reason: string): JsEventReceipt
  drainDelegatedSessions(parentSessionId?: string | undefined | null): Array<string>
  cleanupDelegatedResourcesJson(): string
  delegatedSessionStatusJson(delegatedSessionId: string): string
  registerPlatformAdapter(registration: JsPlatformAdapterRegistration): number
  submitBrainTextDelta(wakeId: string, sessionId: string, text: string): JsEventReceipt
  injectExternalEvent(eventJson: Buffer): JsEventReceipt
  injectDenDataUpdate(updateJson: Buffer): JsEventReceipt
  subscribeEvents(subscription: JsEventSubscription): number
  unsubscribeEvents(handle: number): void
  drainSubscriptionEvents(handle: number, maxEvents: number): Array<string>
  submitBrainEvent(wakeId: string, sessionId: string, eventType: string, text?: string | undefined | null, toolName?: string | undefined | null, isError?: boolean | undefined | null, metadataJson?: string | undefined | null): JsEventReceipt
  get manifestVersion(): number
  get operationNames(): Array<string>
  get wireShapeFingerprint(): string
  listProfileMemory(query: JsProfileMemoryQuery): Array<JsProfileMemoryRecord>
  listMemorySpaceDescriptorsJson(): string
  querySessionMemoryRecordsJson(inputJson: string): string
  buildSessionMemoryPromptContextJson(inputJson: string): string
  saveMemoryProposalJson(inputJson: string): string
  planCaptureMemoryProposalsJson(inputJson: string): string
  planCuratorGovernanceTransitionJson(inputJson: string): string
  planCuratorLifecycleTransitionJson(inputJson: string): string
  planBackgroundMemoryAutoMutationsJson(inputJson: string): string
  listMemoryProposalsJson(inputJson: string): string
  saveSessionActivityDigestJson(inputJson: string): string
  listSessionActivityDigestsJson(inputJson: string): string
  saveContextCompactionArtifactJson(inputJson: string): string
  listContextCompactionArtifactsJson(inputJson: string): string
  recordMemoryGovernanceDecisionJson(inputJson: string): string
  getProfileMemory(profileId: string, targetType: string, targetId: string | undefined | null, key: string): JsProfileMemoryRecord | null
  addProfileMemory(write: JsProfileMemoryWrite): JsProfileMemoryRecord
  replaceProfileMemory(replace: JsProfileMemoryReplace): JsProfileMemoryRecord
  removeProfileMemory(delete: JsProfileMemoryDelete): JsProfileMemoryRecord
  startPiAgentBrainJson(inputJson: string): string
  drainPiAgentBrainStreamJson(wakeId: string, maxItems?: number | undefined | null): string
  submitPiAgentToolOutputJson(inputJson: string): string
  cancelPiAgentBrainJson(inputJson: string): string
  runOpenaiResponsesBrainJson(inputJson: string): Promise<unknown>
  exchangeOpenaiOauthCodeJson(inputJson: string): Promise<unknown>
  startOpenaiResponsesBrainJson(inputJson: string): string
  drainOpenaiResponsesBrainStreamJson(wakeId: string, maxItems?: number | undefined | null): string
  submitOpenaiResponsesToolOutputJson(inputJson: string): string
  cancelOpenaiResponsesBrainJson(inputJson: string): string
  planRoleplayAssistantAlternativeJson(inputJson: string): string
  planRoleplaySessionLifecycleJson(inputJson: string): string
  planRoleplayChatLayerBindingJson(inputJson: string): string
  normalizeRoleplayLoreSearchControlsJson(inputJson: string): string
  readRoleplaySceneStateJson(inputJson: string): string
  planRoleplaySceneStateUpdateJson(inputJson: string): string
  buildRoleplayPromptContextJson(inputJson: string): string
  roleplaySpeakerIdentityJson(inputJson: string): string
  writeRoleplayCharacterJson(inputJson: string): string
  mergeRoleplayCharacterJson(inputJson: string): string
  writeRoleplayPlayerPersonaJson(inputJson: string): string
  mergeRoleplayPlayerPersonaJson(inputJson: string): string
  patchRoleplaySessionMetadataJson(inputJson: string): string
  normalizeRoleplayNarratorConfigJson(inputJson: string): string
  roleplayNarratorMandatoryExploreRequestsJson(inputJson: string): string
  roleplayNarratorAutoCaptureRequestJson(inputJson: string): string
  startRoleplayNarratorTurnJson(inputJson: string): string
  nextRoleplayNarratorPhaseJson(inputJson: string): string
  roleplayNarratorReviewRequestsRevision(feedback: string): boolean
  addLoreEntryJson(inputJson: string): string
  replaceLoreEntryJson(inputJson: string): string
  supersedeLoreEntryJson(inputJson: string): string
  tombstoneLoreEntryJson(inputJson: string): string
  queryLoreEntriesJson(inputJson: string): string
  getLoreEntryJson(recordId: string): string
  loreEntryProvenanceEventsJson(recordId: string): string
  createLoreLayerJson(inputJson: string): string
  getLoreLayerJson(layerId: string): string
  listLoreLayersJson(profileId: string): string
  updateLoreLayerJson(inputJson: string): string
  archiveLoreLayerJson(inputJson: string): string
  getLoreLayerConfigJson(layerId: string): string
  setLoreLayerConfigJson(inputJson: string): string
  addEntryToLayerJson(inputJson: string): void
  removeEntryFromLayerJson(inputJson: string): void
  setEntryConstantJson(inputJson: string): void
  listEntriesByLayerJson(layerId: string): string
  captureLoreFactJson(inputJson: string): string
  promoteLoreEntryJson(inputJson: string): string
  setChatLayersJson(inputJson: string): void
  getChatLayersJson(chatId: string): string
  toggleChatLayerJson(inputJson: string): void
  reorderChatLayersJson(inputJson: string): void
  recallLoreJson(inputJson: string): string
  listRecallTracesJson(inputJson: string): string
  getRecallTraceJson(traceId: string): string
  registerScheduledWakeJobJson(jobId: string, targetSessionId: string, intervalMs: number | undefined | null, firstDueAt: string): string
  registerScheduledHostJobJson(jobId: string, jobKind: string, intervalMs: number | undefined | null, firstDueAt: string, payloadJson: string): string
  listScheduledJobsJson(status?: string | undefined | null, jobKind?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): string
  listScheduledRunsJson(jobId?: string | undefined | null, status?: string | undefined | null, trigger?: string | undefined | null, targetSessionId?: string | undefined | null, limit?: number | undefined | null, offset?: number | undefined | null): string
  claimScheduledHostRunsJson(supportedJobKinds: Array<string>, limit?: number | undefined | null): string
  requestScheduledHostJobRunJson(jobId: string, supportedJobKinds: Array<string>): string
  completeScheduledHostRun(runId: string, status: string, outputJson: string, error?: string | undefined | null): void
  runSchedulerTickJson(): string
  requestScheduledJobRunJson(jobId: string): string
  pauseScheduledJob(jobId: string): void
  resumeScheduledJob(jobId: string, nextDueAt: string): void
  registerBrainImplementation(registration: JsBrainImplementationRegistration): number
  replaceBrainImplementation(registration: JsBrainImplementationRegistration): number
  unregisterBrainImplementationForProfile(profileId: string): number
  buildBrainWakeRequest(brain: number, sessionId: string, bodyStateJson: Buffer, systemPrompt: string, roleAssemblyJson: Buffer, wakeId: string): JsBufferedBrainWakeRequest
  buildBrainWakeRequestForSession(brain: number, sessionId: string, systemPrompt: string, roleAssemblyJson: Buffer, wakeId: string): JsBufferedBrainWakeRequest
  applyBrainProviderStateOutputJson(brain: number, sessionId: string, wakeId: string, outputJson: string): void
  providerStateDiagnostics(limit?: number | undefined | null): Array<JsProviderStateDiagnostic>
  getBuffer(handle: number): JsRuntimeBufferView
  releaseBuffer(handle: number): void
  assertNoBufferLeaks(): void
  createSession(config: JsSessionConfig): JsSessionState
  ensureConfiguredSession(config: JsSessionConfig): JsSessionState
  archiveSession(sessionId: string): JsSessionState
  listSessionsJson(): string
  routeAgentMessage(from: string, to: string, body: string, correlationId?: string | undefined | null): JsEventReceipt
  enqueueBodyFollowUpMessage(sessionId: string, from: string, body: string, correlationId?: string | undefined | null): JsQueuedMessageRecord
  projectBodyStateJson(sessionId: string): Buffer
  submitBrainActionsJson(wakeId: string, sessionId: string, actionsJson: Buffer): JsActionBatchReceipt
  countRows(table: string): number
  databaseSize(): JsRuntimeDatabaseSize
  storageDiagnostics(): JsRuntimeStorageDiagnostics
  storageSchema(): JsRuntimeModuleSchemaRegistryDiagnostics
  runMaintenance(policy: JsRuntimeMaintenancePolicy): JsRuntimeMaintenanceReport
  searchRuntime(query: JsRuntimeSearchQuery): Array<JsRuntimeSearchResult>
  queryRuntimeCounters(query: JsRuntimeCounterQuery): Array<JsRuntimeCounterRecord>
  listSimpleKv(query: JsSimpleKvQuery): Array<JsSimpleKvRecord>
  putSimpleKv(write: JsSimpleKvWrite): JsSimpleKvRecord
  deleteSimpleKv(delete: JsSimpleKvDelete): JsSimpleKvRecord
  runtimeSummary(scopeType: string, scopeId?: string | undefined | null): JsRuntimeCounterSummary
  resetRuntimeCounters(query: JsRuntimeCounterQuery): number

  constructor()
  initializeEngine(config: JsEngineConfig): number
  shutdownEngine(engine: number, drainTimeoutMs: number): JsShutdownSummary
  bufferedBrainRunDiagnosticsJson(): string
  cleanupBufferedBrainRunsJson(reasonCode: string, summary: string): string
}

export interface JsActionBatchReceipt {
  wakeId: string
  acceptedActions: number
  rejectedActionsJson: string
}

export interface JsBrainImplementationRegistration {
  implementationId: string
  profileId: string
  toolProfile: JsToolProfile
  modelConfig: JsBrainModelConfig
  strategy?: JsBrainStrategyMetadata
  providerStateScope?: JsBrainProviderStateScope
}

export interface JsBrainModelConfig {
  provider: string
  modelName: string
  temperatureMilli?: number
  maxOutputTokens?: number
}

export interface JsBrainProviderStateScope {
  profileFingerprint: string
  providerFingerprint: string
}

export interface JsBrainProviderStateStrategyMetadata {
  mode: string
}

export interface JsBrainStrategyMetadata {
  moduleId: string
  strategyId: string
  providerState: JsBrainProviderStateStrategyMetadata
}

export interface JsBufferedBrainWakeRequest {
  bodyState: number
  systemPrompt: number
  roleAssembly: number
  providerStateJson?: string
  providerStateAbsence?: string
}

export interface JsEngineConfig {
  engineDataDir: string
  fixedClock?: string
  defaultTurnBudget: number
  defaultIdleTimeoutMs: number
  storageBackend?: string
  postgresDatabaseUrl?: string
  postgresSchema?: string
  postgresMaxConnections?: number
  postgresStatementTimeoutMs?: number
}

export interface JsEventReceipt {
  accepted: boolean
  sequence: number
}

export interface JsEventSubscription {
  eventKinds: Array<string>
  sessionId?: string
  agentId?: string
  adapterId?: string
}

export interface JsPlatformAdapterRegistration {
  adapterId: string
  kind: string
  displayName: string
}

export interface JsProfileMemoryCaps {
  maxRecordsPerProfile?: number
  maxKeyBytes?: number
  maxContentBytes?: number
}

export interface JsProfileMemoryDelete {
  profileId: string
  targetType: string
  targetId?: string
  key: string
  expectedRevision: number
}

export interface JsProfileMemoryQuery {
  profileId: string
  targetType?: string
  targetId?: string
  limit?: number
  offset?: number
}

export interface JsProfileMemoryRecord {
  profileId: string
  targetType: string
  targetId: string
  key: string
  content: string
  metadataJson: string
  revision: number
  createdAt: string
  updatedAt: string
}

export interface JsProfileMemoryReplace {
  write: JsProfileMemoryWrite
  expectedRevision: number
}

export interface JsProfileMemoryWrite {
  profileId: string
  targetType: string
  targetId?: string
  key: string
  content: string
  metadataJson?: string
  caps?: JsProfileMemoryCaps
}

export interface JsProviderStateDiagnostic {
  sessionId: string
  moduleId: string
  strategyId: string
  status: string
  payloadVersion?: string
  payloadBytes?: number
  createdAt?: string
  updatedAt?: string
  expiresAt?: string
  lastWakeId?: string
  invalidatedAt?: string
  invalidationReason?: string
}

export interface JsQueuedMessageRecord {
  messageId: string
  ownerSessionId?: string
  ownerAgentId: string
  fromAgent: string
  toAgent: string
  body: string
  correlationId?: string
  enqueuedAt: string
  expiresAt: string
  ttlMs: number
  deliveryAttempts: number
  state: string
  terminalAt?: string
  stateReason?: string
}

export interface JsResourceLimits {
  workdir?: string
  maxDurationMs?: number
  maxDelegationDepth?: number
}

export interface JsRuntimeBufferView {
  handle: number
  mediaType: string
  byteLen: number
  bytes: Buffer
}

export interface JsRuntimeCounterQuery {
  scopeType?: string
  scopeId?: string
  counterName?: string
  limit?: number
  offset?: number
}

export interface JsRuntimeCounterRecord {
  scopeType: string
  scopeId: string
  counterName: string
  value: number
  updatedAt: string
}

export interface JsRuntimeCounterSummary {
  scopeType: string
  scopeId: string
  brainTurns: number
  wakes: number
  toolCalls: number
  toolErrors: number
  delegationsCreated: number
  delegationsCompleted: number
  delegationsFailed: number
  delegationsTimedOut: number
  delegationsCancelled: number
  messages: number
  completions: number
  queueExpirations: number
}

export interface JsRuntimeDatabaseSize {
  databaseBytes: number
  pageCount: number
  pageSizeBytes: number
  freelistPages: number
  freelistBytes: number
  walBytes: number
}

export interface JsRuntimeInstalledModuleSchemaDiagnostic {
  moduleId: string
  installedVersion: number
  descriptorFingerprint: string
  installedAt: string
  updatedAt: string
}

export interface JsRuntimeMaintenancePolicy {
  expireQueuedMessagesAt?: string
  purgeTerminalQueuedMessagesBefore?: string
  expireProviderWireStatesAt?: string
  compactSessionMemoryAt?: string
  sessionMemoryMaxActiveRecordsPerScope?: number
  sessionMemoryArchiveBatchSize?: number
  runWalCheckpoint?: boolean
  runOptimize?: boolean
}

export interface JsRuntimeMaintenanceReport {
  sizeBefore: JsRuntimeDatabaseSize
  sizeAfter: JsRuntimeDatabaseSize
  expiredQueueMessages: number
  purgedTerminalQueueMessages: number
  expiredProviderWireStates: number
  sessionMemoryCompaction: JsSessionMemoryCompactionReport
  walCheckpointRan: boolean
  optimizeRan: boolean
}

export interface JsRuntimeModuleCapabilityStatus {
  capability: string
  required: boolean
  supported: boolean
  backendVariant?: string
}

export interface JsRuntimeModuleLogicalStoreDiagnostic {
  storeName: string
  description: string
}

export interface JsRuntimeModuleNamedDiagnostic {
  name: string
  description: string
}

export interface JsRuntimeModulePhysicalIndexDiagnostic {
  tableName: string
  purpose: string
  physicalIndex: string
  columns: Array<string>
  unique: boolean
}

export interface JsRuntimeModulePhysicalTableDiagnostic {
  tableName: string
  logicalStore: string
  physicalTable: string
  declaration: string
}

export interface JsRuntimeModuleQueryCatalogDiagnostic {
  queryId: string
  storeName: string
  description: string
  parameterSchemaId?: string
}

export interface JsRuntimeModuleRetentionDiagnostic {
  storeName: string
  policy: string
  detail?: string
}

export interface JsRuntimeModuleSchemaDiagnostic {
  moduleId: string
  ownerCrate: string
  ownerModule: string
  descriptorVersion: number
  installedVersion?: number
  migrationStatus: string
  descriptorFingerprint: string
  installedDescriptorFingerprint?: string
  installedAt?: string
  updatedAt?: string
  capabilityStatus: Array<JsRuntimeModuleCapabilityStatus>
  logicalStores: Array<JsRuntimeModuleLogicalStoreDiagnostic>
  physicalTables: Array<JsRuntimeModulePhysicalTableDiagnostic>
  physicalIndexes: Array<JsRuntimeModulePhysicalIndexDiagnostic>
  retention: Array<JsRuntimeModuleRetentionDiagnostic>
  repositoryContracts: Array<JsRuntimeModuleNamedDiagnostic>
  queryCatalogEntries: Array<JsRuntimeModuleQueryCatalogDiagnostic>
  exportHooks: Array<JsRuntimeModuleTransferHookDiagnostic>
  importHooks: Array<JsRuntimeModuleTransferHookDiagnostic>
  migrationNotes: Array<string>
  degradedReasons: Array<string>
  blockedReasons: Array<string>
}

export interface JsRuntimeModuleSchemaRegistryDiagnostics {
  source: string
  backendCapabilities: Array<string>
  modules: Array<JsRuntimeModuleSchemaDiagnostic>
  orphanInstalledModules: Array<JsRuntimeInstalledModuleSchemaDiagnostic>
}

export interface JsRuntimeModuleTransferHookDiagnostic {
  hookName: string
  formatVersion: number
}

export interface JsRuntimeQueryPlanCheck {
  name: string
  usesIndex: boolean
  detail: string
}

export interface JsRuntimeRepositoryBackendRequirement {
  capability: string
  required: boolean
  detail: string
}

export interface JsRuntimeRepositoryGroupDiagnostic {
  groupId: string
  label: string
  correctnessSensitive: boolean
  backendRequirements: Array<JsRuntimeRepositoryBackendRequirement>
  notes: Array<string>
}

export interface JsRuntimeSearchQuery {
  query: string
  rowType?: string
  sessionId?: string
  agentId?: string
  instanceId?: string
  taskId?: string
  eventKind?: string
  recordedAfter?: string
  recordedBefore?: string
  limit?: number
}

export interface JsRuntimeSearchResult {
  rowType: string
  rowKey: string
  sequence?: number
  sessionId?: string
  agentId?: string
  instanceId?: string
  taskId?: string
  eventKind?: string
  recordedAt: string
  title: string
  body: string
}

export interface JsRuntimeStorageCapability {
  name: string
  supported: boolean
  detail: string
}

export interface JsRuntimeStorageConnectionHealth {
  backend: string
  status: string
  maxConnections: number
  activeConnections: number
  idleConnections: number
  totalOpened: number
  checkoutCount: number
  checkoutReuseCount: number
  reconnectAttempts: number
  reconnectSuccesses: number
  closedConnectionsDiscarded: number
  lastError?: string
}

export interface JsRuntimeStorageDiagnostics {
  backend: string
  backendLabel: string
  schemaVersion: number
  supportedSchemaVersion: number
  migrations: Array<JsSchemaMigrationRecord>
  size: JsRuntimeDatabaseSize
  tableCounts: Array<JsRuntimeStorageTableCount>
  capabilities: Array<JsRuntimeStorageCapability>
  repositoryGroups: Array<JsRuntimeRepositoryGroupDiagnostic>
  connectionHealth: JsRuntimeStorageConnectionHealth
  moduleRegistry: JsRuntimeModuleSchemaRegistryDiagnostics
  indexChecks: Array<JsRuntimeQueryPlanCheck>
  searchHealthy: boolean
  pressureSignals: Array<JsRuntimeStoragePressureSignal>
  pressure: boolean
}

export interface JsRuntimeStoragePressureSignal {
  name: string
  active: boolean
  severity: string
  observedValue: number
  thresholdValue?: number
  detail: string
}

export interface JsRuntimeStorageTableCount {
  table: string
  rows: number
}

export interface JsSchemaMigrationRecord {
  version: number
  description: string
  appliedAt: string
}

export interface JsSessionConfig {
  sessionId: string
  agentId: string
  profileId: string
  kind: string
  resourceLimits?: JsResourceLimits
  toolProfile?: JsToolProfile
  historyWindow?: JsSessionHistoryWindow
}

export interface JsSessionHistoryWindow {
  maxMessages?: number
}

export interface JsSessionMemoryCompactionReport {
  enabled: boolean
  scopesInspected: number
  retentionPressureScopes: number
  scopesCompacted: number
  sessionSummariesCreated: number
  branchSummariesCreated: number
  recordsArchived: number
  recordsSuperseded: number
  skippedScopes: number
}

export interface JsSessionState {
  handle: number
  sessionId: string
  agentId: string
  profileId: string
  kind: string
  status: string
  historyWindow?: JsSessionHistoryWindow
}

export interface JsShutdownSummary {
  archivedSessions: number
  droppedSubscriptions: number
}

export interface JsSimpleKvDelete {
  scopeType: string
  scopeId: string
  key: string
  expectedRevision: number
}

export interface JsSimpleKvQuery {
  scopeType: string
  scopeId: string
  keyPrefix?: string
  includeExpired?: boolean
  expiredOnly?: boolean
  now?: string
  limit?: number
  offset?: number
}

export interface JsSimpleKvRecord {
  scopeType: string
  scopeId: string
  key: string
  valueJson: string
  revision: number
  createdAt: string
  updatedAt: string
  expiresAt?: string
}

export interface JsSimpleKvWrite {
  scopeType: string
  scopeId: string
  key: string
  valueJson: string
  now: string
  expiresAt?: string
}

export interface JsToolDescriptor {
  name: string
  description: string
  inputSchema?: number
}

export interface JsToolProfile {
  tools: Array<JsToolDescriptor>
}
