use anyhow::{bail, Context, Result};
use rusty_crew_core_bridge_api::{MANIFEST_TEXT, MANIFEST_VERSION};
use serde::Serialize;
use std::{fs, path::Path};

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
struct BridgeOperationMetadata {
    name: String,
    surface: String,
    direction: String,
    input: String,
    output: String,
    errors: String,
    summary: String,
}

pub fn bridge_contracts_ts() -> Result<String> {
    let operations = operation_metadata(MANIFEST_TEXT)?;
    let mut output =
        String::from("// @generated by `npm run codegen:bridge-contracts`; do not edit.\n\n");
    output.push_str(&format!(
        "export const bridgeManifestVersion = {MANIFEST_VERSION} as const;\n\n"
    ));
    output.push_str("export const bridgeOperations = [\n");
    for operation in operations {
        let json = serde_json::to_string(&operation)?;
        output.push_str(&format!("  {json},\n"));
    }
    output.push_str("] as const;\n\n");
    output.push_str(
        "export type BridgeOperation = (typeof bridgeOperations)[number];\n\
         export type ManifestOperationName = BridgeOperation[\"name\"];\n\n\
         export const manifestOperationNames = bridgeOperations.map(\n\
           ({ name }) => name,\n\
         ) as readonly ManifestOperationName[];\n\n",
    );
    output.push_str(&format!(
        "export const bridgeWireShapeFingerprint = {:?} as const;\n",
        super::bridge_wire_shape_fingerprint()?
    ));
    Ok(output)
}

pub fn check_bridge_contracts(path: &Path) -> Result<()> {
    let expected = bridge_contracts_ts()?;
    let actual = fs::read_to_string(path).with_context(|| {
        format!(
            "failed to read generated bridge contracts {}",
            path.display()
        )
    })?;
    if actual != expected {
        bail!(
            "generated bridge contract drift detected for {}; run `npm run codegen:bridge-contracts`",
            path.display()
        );
    }
    Ok(())
}

fn operation_metadata(manifest: &str) -> Result<Vec<BridgeOperationMetadata>> {
    let mut operations = Vec::new();
    let mut current = None;

    for line in manifest.lines() {
        let line = line.trim();
        if line == "[[operation]]" {
            if let Some(operation) = current.take() {
                operations.push(finish_operation(operation)?);
            }
            current = Some(OperationDraft::default());
            continue;
        }
        let Some(draft) = current.as_mut() else {
            continue;
        };
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let value = quoted_value(value.trim())?;
        match key.trim() {
            "name" => draft.name = Some(value),
            "surface" => draft.surface = Some(value),
            "direction" => draft.direction = Some(value),
            "input" => draft.input = Some(value),
            "output" => draft.output = Some(value),
            "errors" => draft.errors = Some(value),
            "summary" => draft.summary = Some(value),
            _ => {}
        }
    }
    if let Some(operation) = current {
        operations.push(finish_operation(operation)?);
    }

    let mut names = std::collections::BTreeSet::new();
    for operation in &operations {
        if !names.insert(operation.name.as_str()) {
            bail!("duplicate bridge operation `{}`", operation.name);
        }
    }
    if operations.is_empty() {
        bail!("bridge manifest contains no operations");
    }
    Ok(operations)
}

#[derive(Default)]
struct OperationDraft {
    name: Option<String>,
    surface: Option<String>,
    direction: Option<String>,
    input: Option<String>,
    output: Option<String>,
    errors: Option<String>,
    summary: Option<String>,
}

fn finish_operation(draft: OperationDraft) -> Result<BridgeOperationMetadata> {
    let name = draft.name.context("bridge operation is missing name")?;
    Ok(BridgeOperationMetadata {
        surface: draft
            .surface
            .with_context(|| format!("bridge operation {name} is missing surface"))?,
        direction: draft
            .direction
            .with_context(|| format!("bridge operation {name} is missing direction"))?,
        input: draft
            .input
            .with_context(|| format!("bridge operation {name} is missing input"))?,
        output: draft
            .output
            .with_context(|| format!("bridge operation {name} is missing output"))?,
        errors: draft
            .errors
            .with_context(|| format!("bridge operation {name} is missing errors"))?,
        summary: draft
            .summary
            .with_context(|| format!("bridge operation {name} is missing summary"))?,
        name,
    })
}

fn quoted_value(value: &str) -> Result<String> {
    let value = value
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
        .with_context(|| format!("expected quoted bridge manifest value, found `{value}`"))?;
    Ok(value.to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_bridge_contracts_include_manifest_metadata_and_fingerprint() {
        let generated = bridge_contracts_ts().expect("generate bridge contracts");
        assert!(generated.contains("export const bridgeOperations"));
        assert!(generated.contains("\"name\":\"initialize_engine\""));
        assert!(generated.contains("export const bridgeWireShapeFingerprint"));
    }
}
